title: "#cloudnative #devops #cloud"
logo: /assets/img/logo_transparent.png
description: A DevOps, Cloud and Cloud-Native Stack Consulting Company
show_downloads: false
linkedin_url: https://www.linkedin.com/company/deepnative
google_analytics:
theme: jekyll-theme-minimal
